fileUrl<-"https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(fileUrl,"C:\\Users\\vava\\Desktop\\Statistics\\Exploratory Analysis\\data1.zip")
unzip("C:\\Users\\vava\\Desktop\\Statistics\\Exploratory Analysis\\data1.zip")
electrition<-read.table("data1\\household_power_consumption.txt",sep=";",header=TRUE)
electrition$DateTime<-with(electrition, interaction(Date,Time))
library(lubridate)
electrition$DateTime<-dmy_hms(electrition$DateTime)
projectdata<-subset(electrition, as.Date(as.character(Date), "%d/%m/%Y") %in% as.Date(c("01/02/2007", "02/02/2007"), "%d/%m/%Y"))
projectdata$Global_active_power<-as.numeric(as.character(projectdata$Global_active_power))
projectdata$Sub_metering_1<-as.numeric(as.character(projectdata$Sub_metering_1))
projectdata$Sub_metering_2<-as.numeric(as.character(projectdata$Sub_metering_2))
projectdata$Voltage<-as.numeric(as.character(projectdata$Voltage))
projectdata$Global_reactive_power<-as.numeric(as.character(projectdata$Global_reactive_power))
png(filename="Plot4.png", width=480, height=480)
par(mfcol=c(2,2))
plot(projectdata$DateTime,projectdata$Global_active_power,type="l",ylab="Global Active Power(kilowatts)",xlab="")
plot(projectdata$DateTime, projectdata$Sub_metering_1, type="l", col="black",ylab="Energy sub metering",xlab="")
lines(projectdata$DateTime, projectdata$Sub_metering_2, col="red")
lines(projectdata$DateTime, projectdata$Sub_metering_3, col="blue")
legend(x="topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=c(1,1,1), col=c("black", "red", "blue"))
plot(projectdata$DateTime,projectdata$Voltage,ylab="Voltage",xlab="datetime",type="l",lwd=1)
plot(y=projectdata$Global_reactive_power,x=projectdata$DateTime,xlab="datetime",ylab="Global_reactive_power",type="l")
dev.off()
