fileUrl<-"https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(fileUrl,"C:\\Users\\vava\\Desktop\\Statistics\\Exploratory Analysis\\data1.zip")
unzip("C:\\Users\\vava\\Desktop\\Statistics\\Exploratory Analysis\\data1.zip")
electrition<-read.table("data1\\household_power_consumption.txt",sep=";",header=TRUE)
electrition$Date<-as.Date(electrition$Date,"%d/%m/%Y")
projectdata<-subset(electrition,Date %in% as.Date(c("01/02/2007", "02/02/2007"), "%d/%m/%Y"))
projectdata$Global_active_power<-as.numeric(as.character(projectdata$Global_active_power))
png(filename="Plot1.png", width=480, height=480)
hist(projectdata$Global_active_power,main="Global Active Power",col="red",xlab="Global Active Power(kilowatts)")
dev.off()
